In [2]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [4]:

age = np.array([24,28,32,34,36])
age

array([24, 28, 32, 34, 36])

In [5]:
type(age)

numpy.ndarray

In [8]:
age.ndim

1

In [9]:
age = np.array([[24],[28],[32],[34],[36]])
age

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [13]:
age.shape

(5, 1)

In [11]:
data = np.array([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108],[36,164,80,100]])
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [ ]:
#data[row indices,col indices]

In [ ]:
data[1:,1:]

In [14]:
#     row, columns   --> selecting row and columns
data[ : , 0:1] # selected the age column

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [15]:
np.mean(data[ : , 0:1])  #calculating the average of a specific column

print("Mean: ",np.mean(data[ : , 0:1]))
print("Median: ",np.median(data[ : , 0:1]))
print("standard deviation: ",np.std(data[ : , 0:1]))
print("variance: ",np.var(data[ : , 0:1]))


Mean:  30.8
Median:  32.0
standard deviation:  4.308131845707603
variance:  18.56


In [16]:
np.mean(data[ : , 0:1])

np.float64(30.8)

In [ ]:
data[ : , 0:2] # selecing multiple columns

In [17]:
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [18]:
data[ : , 0:4:2]  # dropping 1st columns by using jump

array([[24, 84],
       [28, 80],
       [32, 75],
       [34, 78],
       [36, 80]])

In [19]:
data[:,0:4:3]

array([[ 24, 100],
       [ 28, 120],
       [ 32, 105],
       [ 34, 108],
       [ 36, 100]])

In [21]:
# creating the data in 1D
x1 = np.random.randint(1,200,3)          # One-dimensional array
x1



array([65, 12, 23])

In [24]:
np.random.choice([1,2,3])

np.int64(3)

In [ ]:
x1.ndim

In [35]:
# creating the data in 2D
x2 = np.random.randint(10,20, size=(3,4))          # two-dimensional array
x2

array([[19, 13, 13, 10],
       [13, 14, 14, 13],
       [19, 16, 15, 14]])

In [27]:
x2.ndim

2

In [41]:
# creating the data in 3D
x3 = np.random.randint(10,20, size=(3,2,4,6))          # three dimensional array
x3

array([[[[13, 11, 16, 14, 16, 16],
         [14, 12, 16, 16, 10, 18],
         [19, 17, 19, 12, 12, 10],
         [18, 10, 17, 10, 15, 18]],

        [[12, 16, 14, 17, 18, 10],
         [10, 17, 13, 10, 10, 13],
         [11, 16, 11, 14, 12, 13],
         [16, 16, 17, 16, 11, 18]]],


       [[[16, 13, 16, 14, 17, 10],
         [15, 17, 16, 18, 15, 14],
         [14, 15, 10, 16, 18, 13],
         [15, 11, 15, 10, 13, 15]],

        [[13, 13, 15, 10, 18, 18],
         [15, 13, 18, 10, 18, 19],
         [14, 17, 19, 15, 18, 12],
         [15, 15, 12, 19, 13, 12]]],


       [[[11, 17, 13, 16, 19, 14],
         [13, 19, 17, 11, 19, 19],
         [10, 15, 19, 17, 10, 12],
         [18, 10, 18, 14, 13, 17]],

        [[11, 14, 14, 10, 14, 14],
         [11, 18, 16, 14, 12, 17],
         [12, 19, 15, 11, 15, 16],
         [14, 12, 15, 12, 18, 11]]]])

In [39]:
x3.ndim

4

In [44]:
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108],
       [ 36, 164,  80, 100]])

In [42]:
type(data)

numpy.ndarray

In [43]:
import pandas as pd

In [48]:
df = pd.DataFrame(data,columns=['Age',"Height","Weight","BP"])
df

Age  Height  Weight   BP
0   24     170      84  100
1   28     168      80  120
2   32     171      75  105
3   34     170      78  108
4   36     164      80  100

In [47]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df.columns = ['Age',"Height","Weight","BP"]
df

array(['Age', 'Height', 'Weight', 'BP', '1', '2', '3'], dtype='<U21')

In [49]:
df.index = ['a','b','c','d','e']
df

Age  Height  Weight   BP
a   24     170      84  100
b   28     168      80  120
c   32     171      75  105
d   34     170      78  108
e   36     164      80  100

In [51]:
df["Age"].mean()

np.float64(30.8)

In [ ]:
print("Mean:"  ,df["BP"].mean())
print("Median:"  ,df["BP"].median())
#print("Mode:"  ,df["BP"].mode())
print("standard deviation:"  ,df["BP"].std())
print("variance:"  ,df["BP"].var())

In [53]:
df.describe()

Age      Height     Weight          BP
count   5.000000    5.000000   5.000000    5.000000
mean   30.800000  168.600000  79.400000  106.600000
std     4.816638    2.792848   3.286335    8.234076
min    24.000000  164.000000  75.000000  100.000000
25%    28.000000  168.000000  78.000000  100.000000
50%    32.000000  170.000000  80.000000  105.000000
75%    34.000000  170.000000  80.000000  108.000000
max    36.000000  171.000000  84.000000  120.000000

In [ ]:
import numpy as np

In [ ]:
np.sqrt(4)

In [ ]:
dir(numpy)